services:
    nginx:
        container_name: ag-new-nginx
        build: ./docker/nginx/
        ports:
            - '${DOCKER_NGINX_PORT:-80}:80'
        links:
            - backend
            - frontend
        volumes:
            - ./:/var/www/html
            - ./logs/nginx:/usr/share/nginx/log/
        depends_on:
            - backend
            - frontend

    backend:
        container_name: ag-new-backend
        volumes:
            - ./backend:/var/www/html/backend
        depends_on:
            - postgres
            - redis

    postgres:
        container_name: ag-new-postgres
        image: postgres:17
        ports:
            - '${DOCKER_POSTGRES_PORT}:5432'
        volumes:
            - ./docker/postgresql/data:/var/lib/postgresql/data
        environment:
            POSTGRES_DB: '${DOCKER_POSTGRES_DATABASE:-Please set database name}'
            POSTGRES_USER: '${DOCKER_POSTGRES_USER:-Please set DB user}'
            POSTGRES_PASSWORD: '${DOCKER_POSTGRES_PASSWORD:-Please set DB password}'

    redis:
        container_name: ag-new-redis
        build: ./docker/redis/
        volumes:
            - ./docker/redis/data:/data
